smartsprout/controllers/atuador_controller.py
from smartsprout.models.db import db
from flask import Blueprint, render_template, request
from smartsprout.models.store.usuario import Usuario
from smartsprout.models.store.produto import Produto
from smartsprout.models.store.venda import Venda
from smartsprout.models.iot.componente import Componente
from smartsprout.models.iot.atuador import Atuador

atuador_ = Blueprint("atuador", __name__, template_folder='templates')
atuadores_valores = []

def usuarios_filtrados_fun():
    usuarios_produtos = (db.session.query(Usuario, Venda, Produto)
                         .join(Venda, Usuario.id == Venda.id_usuario)
                         .join(Produto, Venda.id_produto == Produto.id)
                         .order_by(Usuario.username))

    usuarios_filtrados = {}

    for usuario, venda, produto in usuarios_produtos:
        if venda.id not in usuarios_filtrados:
            usuarios_filtrados[venda] = []
            usuarios_filtrados[venda].append(usuario)
            usuarios_filtrados[venda].append(produto)

    return usuarios_filtrados

@atuador_.route("/configuracoes")
def configuracoes():
    venda = None
    usuarios_filtrados = usuarios_filtrados_fun()

    return render_template("configuracoes.html", venda=venda, usuarios_filtrados=usuarios_filtrados)

@atuador_.route("/configuracoes/atuador_especifico", methods=["POST", "GET"])
def configuracoes_venda():

    id_venda = request.form.get('select_user')
    usuarios_filtrados = usuarios_filtrados_fun()


    componentes = (db.session.query(Usuario, Venda, Produto, Componente, Atuador)
                         .filter(Venda.id == id_venda)
                         .join(Venda, Usuario.id == Venda.id_usuario)
                         .join(Produto, Venda.id_produto == Produto.id)
                         .join(Componente, Produto.id == Componente.id_produto)
                        .join(Atuador, Atuador.id_componente == Componente.id)
                         .all())

    atuadores_valores.append(componentes[0][3])
    atuadores_valores.append(componentes[1][3])

    return render_template(
        "configuracoes.html",
        atuadores_valores=atuadores_valores,
        usuarios_filtrados=usuarios_filtrados)

smartsprout/controllers/gestao_controller.py
from flask import Blueprint, render_template, url_for, request, redirect
from flask_login import login_required

from smartsprout.models.db import db
from smartsprout.models.store.usuario import Usuario
from smartsprout.models.store.produto import Produto
from smartsprout.models.iot.componente import Componente
from smartsprout.models.store.venda import Venda
from smartsprout.forms import FormCriarUsuario, FormEditarUsuario
from smartsprout import bcrypt

gestao_ = Blueprint("gestao", __name__, template_folder='templates')

@gestao_.route("/gestao", methods=['GET', 'POST'])
@login_required
def gestao():
    usuario = None
    form_criarusuario = FormCriarUsuario()
    form_editarusuario = FormEditarUsuario()

    if form_criarusuario.validate_on_submit() and 'botao_submit_criarusuario' in request.form:
        senha_crypt = bcrypt.generate_password_hash(form_criarusuario.senha.data)

        usuario = Usuario(
            username=form_criarusuario.username.data,
            senha=senha_crypt,
            roles=form_criarusuario.roles.data.lower()
        )

        db.session.add(usuario)
        db.session.commit()

    usuarios = Usuario.query.all()

    return render_template(
        "gestao.html",
        usuario=usuario,
        form_editarusuario=form_editarusuario,
        form_criarusuario=form_criarusuario,
        usuarios=usuarios)

@gestao_.route("/gestao/<id_usuario>", methods=['GET', 'POST'])
def gestao_usuario(id_usuario):
    usuario = Usuario.query.get(id_usuario)
    vendas = Venda.query.filter_by(id_usuario=id_usuario).all()

    usuarios_produtos = (db.session.query(Usuario, Venda, Produto, Componente)
                         .filter(Venda.id_usuario == id_usuario)
                         .join(Venda, Usuario.id == Venda.id_usuario)
                         .join(Produto, Venda.id_produto == Produto.id)
                         .join(Componente, Produto.id == Componente.id_produto)
                         .all())

    produtos_filtrados = {}

    for usuario, venda, produto, componente in usuarios_produtos:
        if produto not in produtos_filtrados:
            produtos_filtrados[produto] = []
        produtos_filtrados[produto].append(componente)


    form_criarusuario = FormCriarUsuario()
    form_editarusuario = FormEditarUsuario()

    if form_criarusuario.validate_on_submit():
        senha_crypt = bcrypt.generate_password_hash(form_criarusuario.senha.data)

        usuario = Usuario(
            username=form_criarusuario.username.data,
            senha=senha_crypt,
            roles=form_criarusuario.roles.data.lower()
        )

        db.session.add(usuario)
        db.session.commit()

    if form_editarusuario.validate_on_submit():
        usuario.username = form_editarusuario.username.data
        db.session.commit()

    usuarios = Usuario.query.all()

    return render_template(
        "gestao.html",
        usuario=usuario,
        usuarios=usuarios,
        produtos_filtrados=produtos_filtrados,
        usuarios_produtos=usuarios_produtos,
        form_criarusuario=form_criarusuario,
        form_editarusuario=form_editarusuario)


@gestao_.route("/gestao/venda/<id_usuario>", methods=['GET', 'POST'])
def gestao_venda(id_usuario):
    usuario = Usuario.query.get(id_usuario)
    produtos = Produto.query.filter_by(vendido=False).all()
    componentes = Componente.query.all()

    return render_template("vendas.html", id_usuario=id_usuario, usuario=usuario, produtos=produtos, componentes=componentes)

@gestao_.route("/gestao/venda/<id_usuario>/<id_produto>", methods=['GET', 'POST'])
def gestao_vendido(id_usuario, id_produto):
    venda = Venda(id_usuario=id_usuario, id_produto=id_produto)
    usuario = Usuario.query.get(id_usuario)
    produto = Produto.query.get(id_produto)

    usuario.vendas.append(venda)
    produto.vendas.append(venda)
    db.session.add(venda)
    db.session.commit()

    produto.vendido = True
    db.session.commit()

    produtos = Produto.query.filter_by(vendido=False).all()
    componentes = Componente.query.all()

    return render_template("vendas.html", id_usuario=id_usuario, usuario=usuario, produtos=produtos, componentes=componentes)

@gestao_.route("/gestao/<id_usuario>/excluir", methods=['GET', 'POST'])
def gestao_deletar_usuario(id_usuario):
    usuario = Usuario.query.get(id_usuario)
    vendas = Venda.query.filter_by(id_usuario=id_usuario).first()

    if vendas == None:
        db.session.delete(usuario)
        db.session.commit()

    return redirect("/gestao")

smartsprout/controllers/produto_controller.py
from flask import Blueprint, render_template, url_for, request
from smartsprout.forms import FormProduto
from smartsprout.models.store.produto import Produto
from smartsprout.models.iot.componente import Componente
from smartsprout.models.iot.sensor import Sensor
from smartsprout.models.iot.atuador import Atuador
from smartsprout.models.db import db


produto_ = Blueprint("produto", __name__, template_folder='templates')

@produto_.route("/produtos", methods=['GET', 'POST'])
def produtos():
    produtos = Produto.query.all()
    componentes = Componente.query.all()
    return render_template("produtos.html", produtos=produtos, componentes=componentes)

@produto_.route("/produto/forms_produto", methods=['GET', 'POST'])
def forms_produto():
    form_produto = FormProduto()

    def add_produto_componente_sensor(sensor_value, unidade, topico):
        sensor = Componente(
            nome = sensor_value,
            id_produto = produto.id
        )

        produto.componentes.append(sensor)
        db.session.add(produto)
        db.session.commit()

        sensor_s_ = Sensor(
            unidade = unidade,
            topico = topico,
            id_componente= sensor.id
        )

        sensor.sensores.append(sensor_s_)
        db.session.add(sensor)
        db.session.commit()

    def add_produto_componente_atuador(atuador_value, unidade, topico):
        atuador = Componente(
            nome = atuador_value,
            id_produto = produto.id
        )

        produto.componentes.append(atuador)
        db.session.add(produto)
        db.session.commit()

        atuador_at_ = Atuador(
            unidade = unidade,
            topico = topico,
            id_componente= atuador.id
        )

        atuador.atuadores.append(atuador_at_)
        db.session.add(atuador)
        db.session.commit()

    if form_produto.validate_on_submit():
        #Novo produto
        produto = Produto(nome=form_produto.nome_produto.data)

        #novo sensor ultrassônico
        add_produto_componente_sensor(form_produto.sensor_ultrassonico.data, "cm", "/irrigacao/enviar")
        add_produto_componente_sensor(form_produto.sensor_umidade.data, "%", "/irrigacao/enviar")
        add_produto_componente_atuador(form_produto.rele.data, "V", "irrigacao/receber")
        add_produto_componente_atuador(form_produto.bomba_agua.data, "gpm", "irrigacao/receber")

        produtos = Produto.query.all()
        componentes = Componente.query.all()

        return render_template("produtos.html",  produtos=produtos, componentes=componentes)

    return render_template("forms_produto.html", form_produto=form_produto)


@produto_.route("/deletar_produto/<id_produto>", methods=['GET', 'POST'])
def deletar_produto(id_produto):
    produto = Produto.query.get(id_produto)
    ids_sensores = []
    ids_atuadores = []

    if produto.vendido == False:

        componentes = Componente.query.filter_by(id_produto=produto.id)

        for componente in componentes:
            ids_sensores.append(componente.id)
            ids_atuadores.append(componente.id)

        sensores = Sensor.query.filter(Sensor.id_componente.in_(ids_sensores))
        atuadores = Atuador.query.filter(Atuador.id_componente.in_(ids_atuadores))


        for sensor in sensores:
            db.session.delete(sensor)

        for atuador in atuadores:
            db.session.delete(atuador)

        for componente in componentes:
            db.session.delete(componente)

        db.session.delete(produto)
        db.session.commit()

        produtos = Produto.query.all()
        componentes = Componente.query.all()

        return render_template("produtos.html", produtos=produtos, componentes=componentes)

    produtos = Produto.query.all()
    componentes = Componente.query.all()

    return render_template("produtos.html", produtos=produtos, componentes=componentes)


@produto_.route("editar_produto/<id_produto>", methods=['GET', 'POST'])
def editar_produto(id_produto):
    produto = Produto.query.get(id_produto)
    componentes_forms = Componente.query.filter_by(id_produto=id_produto).all()

    form_produto = FormProduto()

    if request.method == "GET":
        form_produto.nome_produto.data = produto.nome
        form_produto.sensor_ultrassonico.data = componentes_forms[0].nome
        form_produto.sensor_umidade.data = componentes_forms[1].nome
        form_produto.rele.data = componentes_forms[2].nome
        form_produto.bomba_agua.data = componentes_forms[3].nome

    elif form_produto.validate_on_submit() and 'botao_submit_criarproduto' in request.form:
        produto.nome = form_produto.nome_produto.data
        componentes_forms[0].nome = form_produto.sensor_ultrassonico.data
        componentes_forms[1].nome = form_produto.sensor_umidade.data
        componentes_forms[2].nome = form_produto.rele.data
        componentes_forms[3].nome = form_produto.bomba_agua.data

        db.session.commit()

        produtos = Produto.query.all()
        componentes = Componente.query.all()

        return render_template("produtos.html", produtos=produtos, componentes=componentes)

    return render_template("editar_produto.html", id_produto=id_produto, produto=produto, form_produto=form_produto)

smartsprout/controllers/sensor_controller.py
import json
from smartsprout.models.db import db
from flask import Blueprint, render_template, request, current_app
from smartsprout.models.store.usuario import Usuario
from smartsprout.models.store.produto import Produto
from smartsprout.models.store.venda import Venda
from smartsprout.models.iot.componente import Componente
from smartsprout.models.iot.sensor import Sensor
from smartsprout.models.iot.leitura import Leitura
from datetime import datetime
from smartsprout.mqtt_connection import mqtt_client, topic_subscribe

sensor_ = Blueprint("sensor", __name__, template_folder='templates')
sensores_valores = []

def usuarios_filtrados_fun():
    usuarios_produtos = (db.session.query(Usuario, Venda, Produto)
                         .join(Venda, Usuario.id == Venda.id_usuario)
                         .join(Produto, Venda.id_produto == Produto.id)
                         .order_by(Usuario.username))

    usuarios_filtrados = {}

    for usuario, venda, produto in usuarios_produtos:
        if venda.id not in usuarios_filtrados:
            usuarios_filtrados[venda] = []
            usuarios_filtrados[venda].append(usuario)
            usuarios_filtrados[venda].append(produto)

    return usuarios_filtrados


@sensor_.route("/sensores", methods=['POST', 'GET'])
def sensores():
    venda = None
    usuarios_filtrados = usuarios_filtrados_fun()

    return render_template("sensores.html", venda=venda, usuarios_filtrados=usuarios_filtrados)


@sensor_.route("/sensores/sensor_especifico", methods=["POST", "GET"])
def sensores_venda():

    id_venda = request.form.get('select_user')
    usuarios_filtrados = usuarios_filtrados_fun()


    componentes = (db.session.query(Usuario, Venda, Produto, Componente, Sensor)
                         .filter(Venda.id == id_venda)
                         .join(Venda, Usuario.id == Venda.id_usuario)
                         .join(Produto, Venda.id_produto == Produto.id)
                         .join(Componente, Produto.id == Componente.id_produto)
                        .join(Sensor, Sensor.id_componente == Componente.id)
                         .all())

    sensores_valores.append(componentes[0][3])
    sensores_valores.append(componentes[1][3])

    return render_template(
        "sensores.html",
        sensores_valores=sensores_valores,
        usuarios_filtrados=usuarios_filtrados)

smartsprout/templates/configuracoes.html
{% extends"base.html" %}
{% block content%}

{% if current_user.roles == "administrador" or current_user.roles == "operador" %}

    <form class="form-inline" method="post" action="{{ url_for('atuador.configuracoes_venda') }}">
        <div class="row justify-content-center">
            <select class="form-select mt-3 me-2" aria-label="Default select example" name="select_user" id="select_user"
                    style="width: 400px; margin-left: 60px">

              <option selected>Buscar...</option>
                    {% for venda, usuario in usuarios_filtrados.items() %}
                        <option value="{{ venda.id }}">{{ usuario[0].username }} - {{ usuario[1].nome }}</option>
                    {% endfor %}
            </select>
            <button type="submit" class="btn btn-primary me-3 mt-3" style="width:5rem">Buscar</button>
        </div>
    </form>
{% endif %}

{% if atuadores_valores %}
<h1 class="text-center mt-2">Configurações</h1>
<div class="row justify-content-start">
    <div class="container bg-success bg-opacity-10 col-4 mt-4  rounded" style="height: 17rem;">
        <div class="container">
            <div class="text-center bg-success text-white fw-bolder rounded">
                <h1>Comandos</h1>
            </div>
        </div>
            <form class="input-group mb-3 flex-column" method="POST">
                <div class="row justify-content-center">
                    <label class="form-label mt-2 text-center">Tempo de espera</label>
                        <input type="number" class="form-control ms-2 " aria-label="Username" style="width: 15%;"
                        aria-describedby="basic-addon1">
                    <select class="form-select ms-2" id="inputGroupSelect01" style="width: 8rem;">
                        <option selected>Tipo</option>
                        <option value="1">Segundos</option>
                        <option value="2">Minutos</option>
                    </select>
                </div>

                <div class="row justify-content-center">
                    <label class="form-label mt-2 text-center">Tempo Ligado</label>
                    <input type="number" class="form-control " aria-label="Username" style="width: 15%;"
                        aria-describedby="basic-addon1">
                    <select class="form-select ms-2" id="inputGroupSelect02" style="width: 8rem;">
                        <option selected>Tipo</option>
                        <option value="1">Segundos</option>
                        <option value="2">Minutos</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary rounded mt-2 fw-bold">Enviar</button>
            </form>
    </div>

    <!--historico-->

    <div class="container bg-success bg-opacity-10 col-4 mt-4  rounded justify-content-start" style="height: 28rem;">
        <div class="container">
            <div class="text-center bg-success text-white fw-bolder rounded">
                <h1>Histórico</h1>
            </div>
        </div>
        <div class="container overflow-auto bg-white text-black mh-90" style="width: 90%; height: 85%;">
            <p></p>
        </div>
    </div>
</div>

{% endif %}

{% endblock%}

smartsprout/templates/editar_produto.html
{% extends "base.html" %}
{% block content%}

<div class="vertical-center mt-3 ">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="card-body">
                    <form action = "{{ url_for('produto.editar_produto', id_produto=produto.id) }}" method = "post" enctype="multipart/form-data">
                        {{ form_produto.csrf_token }}
                        <div>
                            {{ form_produto.nome_produto.label(class="form-label mt-2 mb-3" ) }}
                            {{ form_produto.nome_produto(class="form-control w-25 mb-4") }}
                        </div>
                        <div>
                            {{ form_produto.sensor_ultrassonico.label(class="form-label mt-2 mb-3" ) }}
                            {{ form_produto.sensor_ultrassonico(class="form-control w-25 mb-4") }}
                        </div>
                        <div>
                            {{ form_produto.sensor_umidade.label(class="form-label mt-2 mb-3" ) }}
                            {{ form_produto.sensor_umidade(class="form-control w-25 mb-4") }}
                        </div>
                        <div>
                            {{ form_produto.rele.label(class="form-label mt-2 mb-3" ) }}
                            {{ form_produto.rele(class="form-control w-25 mb-4") }}
                        </div>
                        <div>
                            {{ form_produto.bomba_agua.label(class="form-label mt-2 mb-3" ) }}
                            {{ form_produto.bomba_agua(class="form-control w-25 mb-4") }}
                        </div>
                        {{ form_produto.botao_submit_criarproduto(class="btn btn-primary rounded mt-2") }}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

smartsprout/templates/gestao.html
{% extends "base.html" %}
{% block content%}

<style>
    .hidden {
        display: none !important;
    }

    .modal-dialog {
        max-width: 100%;
    }

    #navUsuarios {
        width: 15rem;
        min-width: 15rem;
        overflow-y: auto;
        max-height: 100vh;
    }

    #KIT {
        width: calc(100% - 1rem);
    }

    .kit-container {
        height: 60vh;
        overflow-y: auto;
        margin-right: 1rem;
    }
</style>

<div class="d-flex">

    <!-- Usuários cadastrados -->
    <div class="bg-success bg-opacity-10 overflow-auto min-vh-100 border-end border-2 border-success" id="navUsuarios">

        <!-- Lista de usuários -->
        {% for usuario in usuarios %}
            {% if usuario.roles == "comum" %}
                <form action="{{ url_for('gestao.gestao_usuario', id_usuario=usuario.id) }}" method="post">
                    <button type="submit" class="bg-white text-black border border-2 border-secondary border-end-0 mb-1"
                            style="height:4rem; width:100%; text-align:left">
                        <p>ID: {{ usuario.id }}</p>
                        <p>Nome: {{ usuario.username }}</p>
                    </button>
                </form>
            {% endif %}
        {% endfor %}

        <!-- Botão de cadastro -->
        <div class="text-center mt-2">
            <button type="button" class="btn btn-primary text-white fw-bolder mb-2" data-bs-toggle="modal"
            data-bs-target="#cadastroUsuarioModal">
                Cadastrar Usuário
            </button>
        </div>

    </div>


    {% if usuario %}
        <!-- Interface de um usuário X -->
        <div id="usuarioInterface" class="d-flex flex-grow-1 overflow-auto">
            <div class="flex-grow-1">
                <div class="d-flex justify-content-between align-items-center mt-2">
                    <h1 class="text-center flex-grow-1">Informações Gerais</h1>
                    <form action="{{ url_for('gestao.gestao_deletar_usuario', id_usuario=usuario.id) }}" method="post">
                        <button type="submit" class="btn btn-danger me-3" style="height:2.6rem">
                            Excluir
                        </button>
                    </form>
                </div>

                <!--Mostra o nome,ID e o botão de editar-->
                <div class="d-flex justify-content-between align-items-center mt-2 bg-success bg-opacity-10 border-top border-bottom border-2 border-success"
                    style="height: 5rem;">
                    <div>
                        <p class="mt-2 ms-1">ID: {{ usuario.id }}</p>
                        <p class="ms-1">Nome: {{ usuario.username }}</p>
                    </div>
                    <input type="submit" class="btn btn-primary me-3" data-bs-toggle="modal" data-bs-target="#exampleModal"
                        name="/edit_user" value="Editar"/>
                </div>

                <h2 class="text-center">Aparelhos</h2>


                <!-- Adiciona um contêiner com rolagem para os kits -->
                <div class="kit-container">
                    <div class="d-flex justify-content-center align-items-center flex-wrap mt-4 me-3" id="KIT">
                        {% for produto, componente in produtos_filtrados.items() %}
                                <div class="bg-success bg-opacity-10 border border-2 border-success p-3 me-3 mb-3"
                                    style="width: 20%; height: 15rem;">
                                    <div class="d-flex flex-column align-items-center" style="height: 100%;">
                                        <h3 class="mb-3">{{ produto.nome }}</h3>
                                        <div>
                                            <p>{{ componente[0].nome }}</p>
                                            <p>{{ componente[1].nome }}</p>
                                            <p>{{ componente[2].nome }}</p>
                                            <p>{{ componente[3].nome }}</p>
                                        </div>
                                    </div>
                                </div>
                        {% endfor %}

                        <form action="{{ url_for('gestao.gestao_venda', id_usuario=usuario.id) }}" method="post">
                            <button type="submit" class="btn btn-primary p-3 ms-3 mb-3"
                                    style="width: 100%; height: 15rem;" >
                                  <div class="d-flex flex-column align-items-center" style="height: 30%;">
                                      <h3 class="mb-3">Vender Kit</h3>
                                  </div>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!--Interface da edição de usuario-->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered"
                style="display: flex; justify-content: center; align-items: center; min-height: 100vh;">
                <div class="modal-content" style="width: 20rem;">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Usuário</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{{ url_for('gestao.gestao_usuario', id_usuario=usuario.id) }}" class="input-group mb-3 flex-column">
                            {{ form_editarusuario.csrf_token }}
                            <div>
                                {{ form_editarusuario.username.label(class="form-label mt-2") }}
                                {{ form_editarusuario.username(class="form-control", placeholder="Username") }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                                {{ form_editarusuario.botao_submit_editarusuario(class="btn btn-primary") }}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <!-- Interface de cadastro de usuario-->
    <div class="modal" id="cadastroUsuarioModal" tabindex="-1" aria-labelledby="cadastroUsuarioLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg"
            style="display: flex; justify-content: center; align-items: center; min-height: 100vh;">
            <div class="modal-content" style="width: 20rem;">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="cadastroUsuarioLabel">Cadastrar Usuário</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <form class="input-group mb-3 flex-column" action="" method="post">
                        {{ form_criarusuario.csrf_token }}
                        <div>
                            {{ form_criarusuario.username.label(class="form-label mt-2") }}
                            {{ form_criarusuario.username(class="form-control", placeholder="Username") }}
                        </div>
                        <div>
                            {{ form_criarusuario.senha.label(class="form-label mt-2") }}
                            {{ form_criarusuario.senha(class="form-control", placeholder="Senha") }}
                        </div>

                        <div>
                            {{ form_criarusuario.roles.label(class="form-label mt-2") }}
                            {{ form_criarusuario.roles(class="form-control") }}
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                            {{ form_criarusuario.botao_submit_criarusuario(class="btn btn-primary mt-1") }}
                         </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

smartsprout/templates/home.html
{% extends"base.html" %}
{% block content%}

{% endblock%}

smartsprout/templates/produtos.html
<!--sensors.html -->
{% extends "base.html" %}
{% block content%}

<div class="vertical-center">
    <div class="container view">

      <div class="justify-content-center position-absolute top-50 start-50 translate-middle">

        {% if produtos|length> 0 %}
          <table id="view_products" class="table table-striped table-bordered" style="width:100%">
            <p>Produtos</p>
            <thead>
              <tr>
                  <th>Nome</th>
                  <th>Sensor ultrassônico</th>
                  <th>Sensor de umidade</th>
                  <th>Relê</th>
                  <th>Mini bomba d'água</th>
                  <th>Vendido</th>
              </tr>
            </thead>

            <tbody>
                  {% for produto in produtos %}
                      <tr>
                          <td>{{ produto.nome }}</td>

                          {% for componente in componentes %}

                            {% if componente.id_produto == produto.id %}
                              <td>{{ componente.nome }}</td>
                            {% endif %}

                          {% endfor %}

                          <td>{{ produto.vendido }}</td>

                          <td>
                            <form method="post" action="{{ url_for('produto.editar_produto', id_produto=produto.id) }}">
                              <button type="submit" class="btn btn-link">Editar</button>
                            </form>
                          </td>

                          <td>
                            <form method="post" action="{{ url_for('produto.deletar_produto', id_produto=produto.id) }}">
                              <button type="submit" class="btn btn-link">Deletar</button>
                            </form>
                          </td>
                      </tr>
                  {% endfor %}
            </tbody>
          </table>

          <form  action= "/produto/forms_produto">
            <p><input type= "submit" value= "Adicionar produto"/></p>
          </form>

          <form  action= "/home">
              <p><input type= "submit" value= "Retornar"/></p>
          </form>

        {% else %}
          <p>Ainda não há produtos registrados!<p>
          <form  action= "/produto/forms_produto">
            <p><input type= "submit" value= "Adicionar produto"/></p>
          </form>
        {% endif %}
      </div>
  </div>
</div>


{% endblock%}